services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: emapi
    ports:
      - "8095:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: emapidb
    ports:
      - "3303:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: emapidb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: {}
